### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rnixx** [conestack/conestack.development#2]
- [x] Use web test runner instead of karma (cone.\*, yafowil.widget.\*)
- [x] Use mxmake in all packages
- [ ] Drop remaining py27 support
- [ ] Apply ruff and isort to all packages
- [x] Update all packages to pyproject.toml and new style namespace packages
- [ ] Add typing to all packages and use mypy
